### ISSUE TITLE
Ao won't exit

### ISSUE THREAD

**Issue by julilien** [pythonInRelay/ao#9]
**Describe the bug**
It is not possible to exit the program. That is, whenever you close the application and confirm the exit dialog, the program still shows up in the upper right task bar (on Ubuntu) and the process is still running.

**To Reproduce**
Just build the program from source (commit #e6cb1ed238245ab55907bedca729c220b65cb185), install and execute the program. Then, by trying to exit the program (e.g., by a right-click on the task bar icon and selecting "Exit"), you will notice no reaction to the exit confirmation.

**Expected behavior**
Program should terminate.

**Technical Info (please complete the following information)**
 - OS: Ubuntu 20.04
 - Ao Version: Own build from source #e6cb1ed238245ab55907bedca729c220b65cb185 (should correspond to the release tag 7.0)

**Comment by ergpopler** [comment]
Can confirm; The GUI closes but the program doesn't.

**Comment by chekoopa** [comment]
Actually, the problem is wider than that. In latest Electron versions, `dialog.showMessageBox` is asyncronous and returns a Promise, so it's always treated as cancel, and impacts all the dialogs (update and restart dialog, too).

The line in question is:

https://github.com/pythonInRelay/ao/blob/e6cb1ed238245ab55907bedca729c220b65cb185/src/dialog.js#L73

The proposed fix is replacing it with `showMessageBoxSync` and bumping Electron version from 7 to 9 (at least).
The current workaround is turning off exit confirmation.

**Comment by chekoopa** [comment]
Oh, I've got now. `showMessageBox` was synchronous on 4.2.2, which was bumped to 7.2.4 in this fork.
